name: Run Robot Framework Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify dependencies
      run: |
        pip show robotframework
        pip show robotframework-seleniumlibrary
        pip show selenium
        pip show requests

    # - name: Verify Robot Version
    #   run: |
    #     robot --version
    # above line causes "Error: Process completed with exit code 251."
    # My Issue => https://github.com/robotframework/robotframework/issues/5184

    - name: Run Robot Framework tests
      run: |
        robot --loglevel DEBUG --outputdir results tests/

    # - name: Upload Robot Framework results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: robot-tests-results
    #     path: results/
